title: CRUP
description: A starter template using the Just the Docs theme
theme: just-the-docs

url: "https://anikasikka.github.io"
baseurl: "/crup"   

aux_links:
  "View on GitHub": "https://github.com/anikasikka/crup"
